version: "2"

services:
  webm2:
    container_name: m2
    restart: always
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
     - "8000:80"
     - "8443:443"
     - "8001:81"
     - "33060:3306"
     - "2222:22"
